export const HOST = "http://localhost:5000"
export const registerRoute = `${HOST}/api/auth/register`
export const loginRoute = `${HOST}/api/auth/login`;
export const setAvatarRoute = `${HOST}/api/auth/setavatar`
export const allusersRoute = `${HOST}/api/auth/allusers`
export const logoutRoute = `${HOST}/api/auth/logout`
export const messageRoute = `${HOST}/api/messages/addmessages`
export const getAllMessagesRoute = `${HOST}/api/messages/getmessages`